### ISSUE TITLE
Impossible to find media in Rundown

### ISSUE THREAD

**Issue by ovnicola** [jaskie/PlayoutAutomation#115]
Hello Jaskie,

Play TV is a great project!!! With my team we have to create a media channel. We want to use the TV Play solution but we encounter a problem importing video files into the conductor. I managed to ingest my files from my watchfolder to the media folder of the caspar cg. When I look at the media folder of the caspar I can find my media. Unfortunately I don't see any media in the TV Play app. I am a little lost... 

ingest done : 
![image](https://user-images.githubusercontent.com/129307051/228586157-6d780acf-6c7c-4bc8-89bf-67ad4343f632.png)

rundowns : 
![image](https://user-images.githubusercontent.com/129307051/228586304-6fca945a-69e5-4740-9eab-1718b07deaa3.png)

media caspar cg : 
![image](https://user-images.githubusercontent.com/129307051/228586575-ff09bb29-96c0-432e-8124-756734ca5d97.png)

**Comment by jaskie** [comment]
The "search for media" dialog also checks framerate of  the movies against engine settings, to be sure that video is as fluent as possible. Just check the video format of the ingested movies and compare it with engine format. If these formats have different framerates (i.e. 50 vs 60), it will be filtered out of the dialog. In this case it's recommended to convert the movies using external software to correct framerate using pattern "I know how to do this".
We had many cases when playout operators were not aware of this, and played video was not fluent, thus were complaints from channel management.
You can also manually set (wrong) video format for the movies to match engine (and relevant CasparCG channel), then movies should be visible in the dialog, but playout will be strobbed.
Let me know if it's clear :-)

**Comment by ovnicola** [comment]
Hello Jaskie, 

This actually solved most of the problem, thank you very much. I now have a new question, does TVPlay accept MPEG-TS input media that is being written simultaneously? Because concretely, we receive a stream in NDI which is then recorded in MPEG-TS from another software and which I would like to play from TVPlay with a slight delay?

If not, is it possible from TVPlay to retrieve this NDI stream in the conductor?

Thanks in advance,

:-)
