### ISSUE TITLE
Small bug in example code

### ISSUE THREAD

**Issue by mjl38** [jaskie/PlayoutAutomation#117]
Hi,
Thank you VERY much for your example (shown in Visual Studio for the Write() command of Advantec PCI-cards). It's been very helpful. https://github.dev/jaskie/PlayoutAutomation/blob/04fa23ee8bb29abc4d50e94a2e2d847700fcba4f/Plugins/TAS.Server.Advantech/Model/AdvantechDevice.cs#L48#L60

However, I think that this line: 
"return _do.Write(**portValue**, portValue) == ErrorCode.Success;"
in the Write() function, is incorrect.

If I'm not mistaken, It should be:
"return _do.Write(**port**, portValue) == ErrorCode.Success;"

kind regards,
MiguelL

**Comment by jaskie** [comment]
Thanks, it's not an example, it might be in use in production. However it's unlikely, because it's related to standard definition video aspect ratios.
Kind regards,
Jerzy

**Comment by mjl38** [comment]
I did a .Net DLL for someone. They have a PCI-1761 card that previously they could activate/deactivate using some API DRV_Outp(...). No longer works on Win10 and later, so I used your code. It is VERY likely to be a bug, because for them it did not work, and after me changing the first parameter to use Port, intead of PortValue, it now works.
Just my 2cts.
regards.
