### ISSUE TITLE
Live streaming video as live source event

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#13]
Hi,

it will be great if there is a possibility of adding live video event from internet streaming source.

lots of options like zixi feeder, teradek VidiU.
Regards,

Fahad

**Comment by jaskie** [comment]
It's CasparCG-related feature, so its possibility depends on it. For seamless play-out, I suggest to load the live stream to separate CasparCG channel and play it using route producer (i.e. `play 1-16 route://2`  where `2` is the separate channel number). To use the feature within TVPlay, set the `route://2' as live device name for a channel in Servers section of `TVPlay.config.exe`.
