### ISSUE TITLE
Apple ProRes and DVPAL codec

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#15]
Hi Jaskie,

Can use Apple Prores and DVPAL exported from Quicktime for video playback.

Also need to ask you that is it possible to access the rundown from two different machines Like i have three different playout engines and sometime i need to control three of them from one playout client.

it is also observed that some time the playlist counter not accurate on client side. sometime also application got hanged due to network failure and suddenly it will fine after network connection estalished but rundown counter not properly work.

Regards,

Fahad

**Comment by jaskie** [comment]
Fahad,
Usability of particular codec depends on its FFMpeg support. Both of them are supported, so it should work OK. However, mind the audio channel layout - they should contain single stereo audio stream. If not, only first audio stream will be taken and converted to stereo. I.e. DV25 MXF files from XDCAM have independent 4 mono audio channels. Such files would be converted using ingest of TVPlay to correct this.

I'm currently working on RPC functionality that would allow multiple clients.

Can you provide me with some more info (screenshots, instructions to reproduce) the playlist counter issue? At best to my work mail visible [here](https://github.com/jaskie).
Kind regards,
Jurek
