### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Ribeiro60** [jaskie/PlayoutAutomation#16]
Hi, 

Your playout System requirements *Blackmagic Design Decklink as inputs and outputs cards.

it's means that it is not possible to test with just the screen? 

Kind regards Ribeiro

**Comment by faridpo** [comment]
Ribiero,

You want wnat to know the BM cards?

Merry xmas

**Comment by jaskie** [comment]
@Ribeiro60: No, you can configure screen consumer in CasparCG and try without any live input.
