### ISSUE TITLE
CG elements

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#17]
Kindly define how to use cg elements with in playlist.

• can i use cg element with any scheduled clip in playlist with ease in and ease out transition.

Thanks

Fahad

**Comment by jaskie** [comment]
Fahad,
currently CG elements controller works only as a template controller to make your own, however I plan to slightly modify it to make it possible to execute custom commands on CasparCG servers - that would be enough to make it operational in most use cases.
I'll notify here when it will be ready.
Regards,
Jurek

**Comment by jaskie** [comment]
The `TAS.Server.CGElementsController.dll` is now able to add logo and parental signs. Its configuration is in `Configuration\Elements.xml` file.
