### ISSUE TITLE
Newtek NDI

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#18]
Hi,

The Newtek NDi is a very good implementation from Newtek Casparcg also supports
it will be very great feature if you can interface it. specially for recieving and playout live stream from mobile video streaming.

Regards,

Fahad

**Comment by jaskie** [comment]
It's now in both (official and out fork) implementations of CasparCG, however it requires a separate input channel on CasparCG to fluently switch to the live stream.
