### ISSUE TITLE
Video clip Pause on last frame

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#19]
Please add clip pause on last frame.

Video clip automatically get paused on last frame of the video.
using this function we can avoid from black frame on-air.

Regards,

Fahad

**Comment by jaskie** [comment]
It's already done. If it's not working as expected, provide me logs from CasparCG and TVPlay as well.

**Comment by sfahadshahzad** [comment]
will check and update you.

Thanks

Fahad
