### ISSUE TITLE
Where is the TAS.Setup mentioned in documentation?

### ISSUE THREAD

**Issue by PlkMarudny** [jaskie/PlayoutAutomation#2]

**Comment by PlkMarudny** [comment]
It is called TVPlay.config

**Comment by jaskie** [comment]
TAS.Setup (namespace and application) has been renamed to TVPlay.config (application) and TAS.Client,Config (namespace).
I amended this [wiki page](https://github.com/jaskie/PlayoutAutomation/wiki/3.-Configuration) accordingly.
