### ISSUE TITLE
Great Fork

### ISSUE THREAD

**Issue by jfindleylab** [jaskie/PlayoutAutomation#20]
For many reason your caspar server runs much faster than the original,  however while your system implement the ffmpeg streaming option? Latest version animation or script option is not available

**Comment by jaskie** [comment]
Thanks for appreciation,
The ffmpeg streaming is working in [latest release](https://github.com/jaskie/Server/releases/latest), at least for udp streams. Just download, follow example casparcg.config as configuration guide. It's also true that this release is based on CasparCG 2.0.6 version, and don't support 2.1 specific functionality, especially HTML producer, but treat this fork as specialized to MCR play-out applications.
For further issues, I just enabled issue tracking on [the fork](https://github.com/jaskie/Server).
