### ISSUE TITLE
IP Streaming

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#21]
Hi,

how can i stream the same video which i am getting from my playlist.

currently i am using another pc with decklink card and using adobe FMLE encoder for live streaming.

Fahad

**Comment by jaskie** [comment]
Fahad,
my current CasparCG fork [release](https://github.com/jaskie/Server/releases/latest) brings UDP streaming.
The casparcg.config consumer entry should be as follows:
```xml
<stream>
     <path>udp://224.0.0.1:5554</path>
     <acodec>aac</acodec>
     <vcodec>libx264</vcodec>
     <narrow>false</narrow>
     <options>tune=zerolatency,preset=veryfast</options>
     <vrate>1024</vrate>
     <arate>128</arate>
</stream>
```
Note that arate (audio bitrate) and vrate are in kilobytes/s. It is possible to stream directly to an local IP address or to a multicast group, as above. 
Options and codec names comes directly from FFmpeg documentation. 
Protocols other than UDP were not tested, so if you want to different format stream, you can use a rewrapper (i.e. another FFmpeg instance) to do this.
Optional `narrow` switch makes stream 4:3 format.
