### ISSUE TITLE
offline rundown editor and "missing" futures....

### ISSUE THREAD

**Issue by zhta1972** [jaskie/PlayoutAutomation#22]
Hi and thank you for the great project !

The only missing futures from you solution for my taste and opinion are : 

A) Offline-external playlist (rundown) editor for use on another computer (or computers) on the network. Preview player and mark-in, mark out editor will be really helpful !

B) Internal video player (and/or) preview at "media" and rundown, when i select a video file.

C) Direct file drug 'n' drop add, in the rundown (and editor).

D) multiple files selection to add in the playlist (rundown) and editor.

E) Drug 'n' drop re- arrange , move  items up and down in the playlist (rundown) , with multiple selection and move.

F) Cue and "hold last frame" in the rundown. Play with the keyboards "spacebar" will be helpfull in news and live shows.

Thank you very much for you time and your great professional build (and built in futures) software !!!

**Comment by jaskie** [comment]
Thanks for encouraging me,
The missing features are not completely missing:
ad A: Indeed, there is no offline rundown editor, but it's possible to make it simultaneously on other PC using TVPlayClient application. The application uses websocket communication to control scheduling engine that is built in TVPlay or TVPlaySvc executables (if enabled in engine configuration).
ad B: There is internal player using NewTek NDI™ plugin (however not yet released in binary form).
ad F: Cue is F2 key, CasparCG holds on last frame on rundown break or end.
