### ISSUE TITLE
What is Line Recording ?

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#24]
Please explain line recording.

Thanks

**Comment by jaskie** [comment]
I meant recording from linear sources - SDI, HDMI, analog component etc. using BMD cards. In fact, the term is similar to line-in, which denotes audio signal level. I will update the wikis to avoid sucha confusion.

**Comment by sfahadshahzad** [comment]
Ohh good very nice feature.


Thanks
