### ISSUE TITLE
Branding, Parentals ETC - How to use?

### ISSUE THREAD

**Issue by sdorpl** [jaskie/PlayoutAutomation#26]
Witam. Jak używać grafiki ekranowej w tym programie?

**Comment by jaskie** [comment]
Pisz do mnie na PM, bo nie wiem, jak odpowiedzieć...

**Comment by sdorpl** [comment]
Mogę na mail? ;)

**Comment by jaskie** [comment]
Dokładnie.

2017-09-14 15:10 GMT+02:00 sdorpl <notifications@github.com>:

**Comment by sdorpl** [comment]
Poszło :)
