### ISSUE TITLE
Can't add video files.

### ISSUE THREAD

**Issue by Nikoxx99** [jaskie/PlayoutAutomation#27]
Look the video
https://www.youtube.com/watch?v=J72gJtTMrt0

**Comment by jaskie** [comment]
Which is engine's video format? To clips be playable, they must have exactly same framerate as engine, so it can be the reason that files are not visible.
2nd problem - database update (false requirement) - known and fixed in current source code.

**Comment by Nikoxx99** [comment]
the videos are mp4 at 29fps, where can i change the engine fps?
so the database update are not required?

**Comment by jaskie** [comment]
Yes, it's false notification.
Look at Engines button in configuration app, channel video format is there.



2017-11-22 19:45 GMT+01:00 Nikoxx99 <notifications@github.com>:

**Comment by Nikoxx99** [comment]
Well, i change the fps, and it work, now i can add the video. but it not appear at casparcg server view...
![capture](https://user-images.githubusercontent.com/8411262/33144680-e8b92aee-cf8b-11e7-9794-bf4082a47910.PNG)

**Comment by jaskie** [comment]
Probably main channel number is set to zero. Set it to caspar's channel as
defined in caspar.config, counting from 1.

2017-11-22 19:49 GMT+01:00 Nikoxx99 <notifications@github.com>:

**Comment by Nikoxx99** [comment]
Ohhh, yes it is set to 2, let me try....

**Comment by Nikoxx99** [comment]
well i change the channel to 1 and....
![capture](https://user-images.githubusercontent.com/8411262/33144860-7c7490ac-cf8c-11e7-84a8-40374a9c260e.PNG)

**Comment by Nikoxx99** [comment]
im doing something wrong?
![capture](https://user-images.githubusercontent.com/8411262/33144922-ac2a2fb4-cf8c-11e7-9a12-31af8a6b8471.PNG)

**Comment by jaskie** [comment]
No, just update channel selection at Engines.

**Comment by jaskie** [comment]
And set Media Folder to exactly same folder as in caspar.config to booth see them.

**Comment by Nikoxx99** [comment]
![capture](https://user-images.githubusercontent.com/8411262/33145069-25c2b350-cf8d-11e7-8217-3c526f6a3ac8.PNG)

**Comment by jaskie** [comment]
Yes, CasparCG don't see the file in its Media folder...

**Comment by Nikoxx99** [comment]
i see thats mean TVPlay only tell CCG how work

**Comment by Nikoxx99** [comment]
let me try

**Comment by jaskie** [comment]
Yes, TVPlay is only controller for CasparCG's.

**Comment by Nikoxx99** [comment]
Done =D its working, hell thats good, now i can tell my boss i finally found a good TV Playout software

**Comment by Nikoxx99** [comment]
Thanks man.
Question, you're thinking to continue develope this software?

**Comment by jaskie** [comment]
Yes, it's still under development. However, any help would be appreciated.
