### ISSUE TITLE
Add file from any directory?

### ISSUE THREAD

**Issue by Nikoxx99** [jaskie/PlayoutAutomation#28]
I wonder if it would be very difficult to add a video from any directory, since it is tedious to have to read and import each file from the CCG media folder, or there is no option given that CCG works that way.

**Comment by jaskie** [comment]
It's included in ingest process, which is composed of:
* file checking,
* describing with additional properties useful in play-out business process,
* sanitizing using rewrapping and recompression (optional),
* copying it to CasparCG media folder(s).

Just register a ingest folder(s) (different than CasparCG media folder), and use it (them) to ingest files to system.
CasparCG preview from these folder(s) is possible if they are available via Windows path from CasparCG instance.
