### ISSUE TITLE
Decklink Quad configuration

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#3]
Hi,

I am using decklink quad with latest decklink drivers all i need is to configure decklink quad channels in my config i tried a lot but no success.

I am going to set my decklink device # 1 as PGM and # 2 as PRV and 3,4 as input is it possible ?

is there any device control option like MCR switcher or router like Evertz and GVG.

Regards,

Fahad

**Comment by jaskie** [comment]
Hi,
first question is related to CasparCG configuration itself. Channels in Caspar are numbered according to its order in casparcg.config file. In the file should be defined decklink consumers linked to specific cards (you can treat DL Quad as 4 independent cards). You can test them with simple PLAY 1-0 BLUE command (where 1 is channel number, later used in TVPlay.config application). To connect input, you should specify "live device name", which is i.e DECKLINK 2. You can test it i.e. with PLAY 1-0 DECKLINK 2 command. 
So, first make the inputs and outputs working in Caspar itself, then apply the configuration to TVPlay.
Second question: No, there is no router control for input preselection or switcher control yet - they were not needed by us. The simplest possible cases are: particular GPO of an Advantech card that are triggered according to rundown (it can be implemented in LocalDevices project), and second case: the BMD devices control, which protocols are relatively well known.
Regards, 
Jurek

**Comment by sfahadshahzad** [comment]
Dear jaskie.

Thank you very much for quick response.

Yes i configured the casparcg as you said and test the tvplay simply
droping some files in rundown.

Regards.

Fahad
On Apr 28, 2016 10:04 PM, "Jerzy Jaśkiewicz" <notifications@github.com>
wrote:

Hi,
first question is related to CasparCG configuration itself. Channels in
Caspar are numbered according to its order in casparcg.config file. In the
file should be defined decklink consumers linked to specific cards (you can
treat DL Quad as 4 independent cards). You can test them with simple PLAY
1-0 BLUE command (where 1 is channel number, later used in TVPlay.config
application). To connect input, you should specify "live device name",
which is i.e DECKLINK 2. You can test it i.e. with PLAY 1-0 DECKLINK 2
command.
So, first make the inputs and outputs working in Caspar itself, then apply
the configuration to TVPlay.
Second question: No, there is no router control for input preselection or
switcher control yet - they were not needed by us. The simplest possible
cases are: particular GPO of an Advantech card that are triggered according
to rundown (it can be implemented in LocalDevices project), and second
case: the BMD devices control, which protocols are relatively well known.
Regards,
Jurek

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/jaskie/PlayoutAutomation/issues/3#issuecomment-215496197>

**Comment by jaskie** [comment]
Can you review such a rundown and make some screenshots? Dropping (omitting?) rundown items must have its cause. It's almost unlikely that it's common software bug, because the system is operating on daily basis in few facilities. Rather it's cause is specific to your configuration or usage. But, definitely, it's worth analyzing.
Regards,
Jurek
