### ISSUE TITLE
Some way to adjust audio to new framerate

### ISSUE THREAD

**Issue by Nikoxx99** [jaskie/PlayoutAutomation#30]
Well, I would like to be able to add my videos to the playlist without having to convert their framerate, I have more than 400 movies all with different framerate and convert it does not seem a viable option.
My question is because programs like DJSYSTEM have the ability to adjust the audio speed to the framerate of the video, if the video is at 23 FPS and the output is at 30 there are no audio problems.
In CCG for some reason if the framerate of the video is not the same as that of the output the sound is desynchronized.

**Comment by jaskie** [comment]
No, this fork of CasparCG supports only files with frame rate specified for particular channel in its configuration. It would be possible to adjust frame rate of played files to the channel frame rate, however it hardly provides broadcast quality results, so it's not implemented.
Anyway, it's better to ask the question on [CasparCG forum](https://forum.casparcg.com).
