### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Nikoxx99** [jaskie/PlayoutAutomation#31]
Leave this video here.
Some issues with playlist and schedule
https://youtu.be/x0BFS4D1C8M

**Comment by jaskie** [comment]
No, almost everything works as designed. MCR play-out have no reason to pause it. The "pause" button is of different meaning - it says _Load_, right? 
To schedule auto-start you should select a **startup rundown** (marked with _Block begin_ bar), and change its startup type to _Automatic_ using the clock button. Only issue is that it shouldn't be allowed to change scheduled date/time for non startup rundowns. Will be fixed on next release, of course.

**Comment by Nikoxx99** [comment]
Should change the icon of load jeje, well no problem bro, but there is no option "Automatic" on dockbar to schedule, only "Manual" and "At fixed time"... 
The software is excellent hope still develop

**Comment by jaskie** [comment]
Yes, I meant "at fixed time".

**Comment by Nikoxx99** [comment]
Still not working :/

**Comment by Nikoxx99** [comment]
![capture](https://user-images.githubusercontent.com/8411262/33212910-14d9e4fc-d0f3-11e7-9c25-ce636de5f98e.PNG)
and now the time is negative lol.

Another question, how can i stop the playlist?

**Comment by jaskie** [comment]
Strange. Just set the date/time and leave the item, it should start unless something other is playing, unless automatic startup is set as _Forced_
To stop playlist click on blue button combo, and then click the button itself. This prevents accidental play-out stopping. Keyboard shortcut is Shift-Break.
