### ISSUE TITLE
TVPlay remote cliente connection throuble

### ISSUE THREAD

**Issue by Nikoxx99** [jaskie/PlayoutAutomation#32]
Console errors.
![captura](https://user-images.githubusercontent.com/8411262/33321383-7cee0afa-d413-11e7-9fde-45e212981933.PNG)

Config

![captura](https://user-images.githubusercontent.com/8411262/33321415-9a4ff41e-d413-11e7-8a04-812f9067e201.PNG)
try also with 127.0.0.1 and doesn´t work.

**Comment by jaskie** [comment]
It's not CasparCG client, but TVPlay (or TVPlaySvc) client. Enable it, set a free local port in TVPlay.config at Engines section. Then bind with this client to running TVPlat or TVPlaySvc instance from the client. It's experimental feature and shouldn't be used in production, however may be useful in some cases.
