### ISSUE TITLE
How add a logo

### ISSUE THREAD

**Issue by Nikoxx99** [jaskie/PlayoutAutomation#33]
I understand that you can add a logo or a CG to a specific clip, but I really tried and did not manage to do it
https://i.imgur.com/NyNfG1l.png

**Comment by jaskie** [comment]
Short answer: it depends how do you would like to do it.
Slightly longer: 
You can ingest (using a ingest folder) a .png or .tga file (with resolution of full video frame), and then add it to clips using these 1, 2, 3 buttons.
As an alternative, you can build a CG-inserting system based on CGElementsController project, and use data provided under CG check box. Currently, CGElementsController is a functional example, however it's not released in binaries yet.

**Comment by faridpo** [comment]
Jaskie,
Question, if i put a flash cg in to the cgelements, the command is the
same?

**Comment by jaskie** [comment]
No, in that case you have to use the CGElementsController 
or 
add a animation event (it's under "A" button, assuming you have it configured properly).

**Comment by faridpo** [comment]
Mean cg elements control can add a flash animation?

**Comment by jaskie** [comment]
Yes, but it requires some coding. The CGElementsController is only scaffold for something more universal...

**Comment by faridpo** [comment]
Jurek, oke

The cg element is more user friendly to work and program

The A butom need more.. Let say to add a comming next,

**Comment by jaskie** [comment]
Indeed. The animation adding should be easier in most cases.

**Comment by Nikoxx99** [comment]
it be good that you can add the logo to all the rundown

**Comment by Nikoxx99** [comment]
![2017-12-05_10-17-08](https://user-images.githubusercontent.com/8411262/33614493-7dc71ede-d9a5-11e7-9614-5a84ecf34e22.png)
btw that button of logo? its tha same om 1, 2, 3 buttons?

**Comment by jaskie** [comment]
No, these are from the CGElementsController, thus are not operational in current binaries release, however them will be on next. 
Concept of the CGElementsController is that this is a "device" which sets CG properties to particular values (e.g. Logo=0 "none") if enabled for a clip when it starts. If subsequent clip does not have CG checkbox checked, this "device" state remains, therefore whole rundown would be operating with one-time logo set.

**Comment by jaskie** [comment]
A little self-correction. Operational CGElementsController IS included in current binaries. Please, refer to Elements.xml file to set names of pngs.
