### ISSUE TITLE
GPI Triggering

### ISSUE THREAD

**Issue by gluzania** [jaskie/PlayoutAutomation#37]
Hi, How can I trigger videos to play using GPI?
I would like to run a 24/7 station and play ads using your software.

Thanks.

**Comment by jaskie** [comment]
Currently, an GPI can only trigger play-out of loaded (visible at output at first frame) and subsequent clips. This can be done using an Advantech GPI card (i.e. [PCIe-1730](http://www.advantech.com/products/1-2mlkb0/pcie-1730/mod_6d7a4820-cf93-4f6b-bc3a-09d4e1ca62bc)). 
To use it, `TAS.Server.LocalDevices.dll` should be loaded from `plugins` directory with appropriate configuration in `Configuration\LocalDevices.xml` file. As far I remember, the compiled .dll file is not included in release, so I can publish it separately and assist you to make this running.
Currently there are no specific means to break play-out to play ads at arbitrary position, however please describe your use case. It may be simple...

**Comment by gluzania** [comment]
Thanks for the reply.

I would like to use your software to run a 24/7 TV network that allows us to play local spots in between the breaks.

The network sends us DTMF cue tones that I can convert with a DTMF to GPi converter.

I would like to use your software to play the breaks when allowed and then return to network programming.

Thanks.

Gus

**Comment by jaskie** [comment]
So, start from still (at beginning of local air time) is already done, but it requires manual operation to prepare every entry. Is it sufficient? Return to network program should also be done manually, which (as I think) is right operation method. Am I right? Only prepare the .dll?

**Comment by gluzania** [comment]
Yes, we can create our playlist, but we would like them to trigger using GPI and then return to network programming using GPI as well.

Thanks.

**Comment by jaskie** [comment]
It's seems to me that full implementation of such feature (= starting different rundowns based on GPI without continuous human assistance) does not fit in the system's purpose and therefore isn't in our schedule. However, if you'll decide to code it based on this system, a pull request would be welcomed.
