### ISSUE TITLE
Error trying to create a rundown

### ISSUE THREAD

**Issue by Nikoxx99** [jaskie/PlayoutAutomation#38]
![capture](https://user-images.githubusercontent.com/8411262/36789345-33caeef8-1c5f-11e8-8c7d-b9c5af328b3a.PNG)
Windows 10 as OS
Intel i5 3rd gen
12gb RAM
Nvidia GT 210

**Comment by Nikoxx99** [comment]
Plus database is detected but can´t be writed
![capture](https://user-images.githubusercontent.com/8411262/36789773-b1c2f08e-1c60-11e8-91b3-01691e72490f.PNG)
can't create a new one

**Comment by jaskie** [comment]
First issue: what was clicked?
Second: please, check value in only field of `params` table in database norte and existence of `aco` table using MySql Workbench.

**Comment by jaskie** [comment]
Second: It seems to be working OK, steps: 
- add new database,
- provide connection parameters and collation,
- OK creates the new one and user is asked if the new database should be the current one.
If problem persists, pls provide more detailed steps to reproduce it.

**Comment by Nikoxx99** [comment]
First: i clicked the "Add new movie inside" (fisrt button on rundown menu)
second: aco table exist and value fueld of params table seems... good, really i don't know what you mean.
![capture](https://user-images.githubusercontent.com/8411262/36790537-23eab262-1c63-11e8-8bca-894a3a191f95.PNG)
(norte db is now "xd" database)

**Comment by Nikoxx99** [comment]
If you want i can give you acces via TeamViewer

**Comment by jaskie** [comment]
Can't use it at workplace.

**Comment by Nikoxx99** [comment]
So, i can make a little video show you the steps i follow and config i have

**Comment by jaskie** [comment]
First: probably server directory isn't defined properly (check on "Media" tab, configure in Servers section of config program.
Second: this (`xd`)database should'nt ask for update, as it's  up-to-date.

**Comment by Nikoxx99** [comment]
Nevermind, i found the error. the media folder was in a write-protected location.
