### ISSUE TITLE
Where CG Controller in Version 1.3?

### ISSUE THREAD

**Issue by sdorpl** [jaskie/PlayoutAutomation#39]
Where is CG Controller (Logos, Parentals etc.) in v 1.3 ? On version 1.2 it is and works.
https://imgur.com/Z9ASVYV
https://imgur.com/AkuudL9

**Comment by jaskie** [comment]
Just delete TAS.LocalDevices.dll from plugins directory. It breaks plugin load chain if Advantech dll is missing.
