### ISSUE TITLE
Commercials playout server

### ISSUE THREAD

**Issue by eZov** [jaskie/PlayoutAutomation#41]
Hi Jerzy,

I have found your project PlayoutAutomation on GitHub, looking for open source solution to play commercials. and it seems powerful open source solution for broadcast playout.
Is it possible to use your solution like commercials playout server? I mean, is it possible to use it in this mode:
(1) prepare lists of commercials (spots) different playout list (blocks)
(2) trigger playout of each block (playlist) manually during the day.

I would like to have this server as playout source for commercials, so it fills main playout in determined time slots.

Thanks for your time,

Best regards,

**Comment by BabsJ** [comment]
That is not my project.

I think you have send this email to wrong person> LOL

Regards

**Comment by jaskie** [comment]
The notification is probably normal GitHub behavior.
Regarding your questions, for future, if they are not actual issues, ask me using direct mail (it's published on my [profile page](https://github.com/jaskie)).
(1) Yes, it is possible.
(2) If you mean "manually" as using keyboard and mouse, yes, too. 
The project is currently main play-out in [our](https://www.tvp.pl) regional branches, so having separate play-outs for it seems unreasonable, unless you're providing only this part of preogramming for local commercial sales.
