### ISSUE TITLE
Custom server commands are not send

### ISSUE THREAD

**Issue by brambox** [jaskie/PlayoutAutomation#42]
It seems that sending custom script to server does not work at all.
Is there any possible way to fix it?
Thanks!

**Comment by jaskie** [comment]
It's rather problem with documentation. 
The commands have slightly different syntax (as we can't specify channel) and are limited to few basic types.
So start with
`PLAY CG4 A_CLIP MIX 25`
or 
`CG CG3 ADD 1 AN_ANIMATION 1`
where CG3, CG4 - layers as defined [here](https://github.com/jaskie/PlayoutAutomation/blob/1c4857130a40bb8c8efc9dd7fa2bee4216e77a5e/TAS.Common/Enums.cs#L67),
and commands are limited to:
- PLAY,
- CG,
- MIXER (FILL, CLIP, CLEAR).
Please, close the issue if it's OK

**Comment by brambox** [comment]
I see. Thank you! These work.
I was trying to get html template like /PLAY 1-27 [HTML]"file:///C:/templates/template1.html" MIX 10/ and also add hls live stream with /PLAY 1-26 "http://address/chanel/1/playlist.m3u8"/ 
They work fine when paste it direct to Caspercg.
If it's possible to add full command or at least presents for html template and live rundown for internet url  will be great.
Thanks!
