### ISSUE TITLE
Connecting  and sending commands to caspar 2.2

### ISSUE THREAD

**Issue by brambox** [jaskie/PlayoutAutomation#46]
I can't seems to get Tvplay to send commands to Casper 2.2 by default.
It says it's connected but no commands will be send.
Now if i run Caspar 2.0.7 and then 2.2 it will start receive commands.
Is there anything i can do to fix it?
Thank you!

**Comment by jaskie** [comment]
Yes, it's true. Current version of CasparCG does not implement most of INFO [AMCP](https://github.com/CasparCG/help/wiki/AMCP-Protocol#info-server) commands, and this is origin of the problem. I just made a quick fix to restore the functionality. 

Check out [this](https://github.com/jaskie/PlayoutAutomation/releases/tag/1.5b) release.
