### ISSUE TITLE
CG Plugin

### ISSUE THREAD

**Issue by medvidekPanda** [jaskie/PlayoutAutomation#47]
Hi, I have a problem with CG Plugin. Everything seems to be OK, but I can't see CG controler. Could you help me please?
<img width="1488" alt="snimek obrazovky 2019-01-08 v 20 34 47" src="https://user-images.githubusercontent.com/46500716/50854358-1bd47f80-1385-11e9-9a7d-1d571da0c9f3.png">
<img width="1493" alt="snimek obrazovky 2019-01-08 v 20 33 32" src="https://user-images.githubusercontent.com/46500716/50854360-1c6d1600-1385-11e9-9e88-9f430c95789e.png">

**Comment by jaskie** [comment]
Did you moved the plugin dll from plugin repository dll to actual Plugins? This has changed to avoid loading unneeded plugins.

**Comment by medvidekPanda** [comment]
No, I'm a fool. I'm sorry for my mistake :-). Thank you and have a nice days.
