### ISSUE TITLE
LOAD & LOADGB command issue causes file not found

### ISSUE THREAD

**Issue by rifqim** [jaskie/PlayoutAutomation#48]
Hi, i have problem when play a video in **Rundown** section. Video file was detected not found. It seems LOAD & LOADGB command in Rundown section just using file name of video, not full with path video.

If the video plays in **Media** section, no issue.

**Example :** 
In Rundown section : **_LOADBG 1-16 "episodeingest" CHANNEL_LAYOUT STEREO\r\n_**
In Media section : **_LOAD 1-48 "C:\\Users\\rifqi\\Downloads\\Video\\Caspar\\episodeingest.mp4" LENGTH 27142 CHANNEL_LAYOUT STEREO\r\n_**

**Error logs :** 
_[0BFCC060] [error]   File not found. No match found for parameters. Check syntax:EPISODEINGEST CHANNEL_LAYOUT STEREO
[0BFCC060] [warning] Failed to execute command: LoadbgCommand
[0BFCC060] [info]    Sent message to 127.0.0.1: 404 LOADBG ERROR\r\n_

Btw, I'm using casparcg server + TVPlay.

See screenshot below for the details.
**- In Rundown section**

![error load command - play rundown](https://user-images.githubusercontent.com/34053772/51616719-4285df00-1f5d-11e9-8a2c-5cc97c0fcc0e.png)
![error load command](https://user-images.githubusercontent.com/34053772/51616720-431e7580-1f5d-11e9-8d43-ac33de47dad5.png)

**- In Media section**

![load command successfully - in media section](https://user-images.githubusercontent.com/34053772/51616721-431e7580-1f5d-11e9-940b-b06b15c8e098.png)

**Comment by jaskie** [comment]
It is only suspicion: is the media folder in in `casparcg.config` and server's media directory same? 
When playing regular files during play-out, it's assumed that files are located in CasparCG's media directory, and therefore only filename (w/o extension) is provided to `LOADBG` command. When previewing a file from ingest directory, full filename is sent. This is nonstandard feature of the CasparCG fork.
Please, verify.

It's very important to distinguish server's media folders, which contain actual playout clips, and ingest folders, which may contain non-playable content that may (or not) be imported (ingested) to the server's folders.

**Comment by rifqim** [comment]
Hi Jaskie, thanks for your reply.
Could you please help me to verify the media configuration of Casparcg and TVPlay configuration that you explain to me?

**- CasparCG Config**

![caspar config](https://user-images.githubusercontent.com/34053772/51659451-15791100-1fdd-11e9-90c4-2f7c6c753b90.png)

**- Ingest Config**

![ingest config](https://user-images.githubusercontent.com/34053772/51659455-1b6ef200-1fdd-11e9-8f99-f61e751f4c42.png)

**- Play-out Config**

![playout config](https://user-images.githubusercontent.com/34053772/51659462-232e9680-1fdd-11e9-9477-e457c8c552c4.png)

Apologize if there are misconfigured :)

**Comment by jaskie** [comment]
CasparCG media folder is configured in casparcg.config in `<paths>` section, usually:

```xml
<paths>
    <media-path>media\</media-path>
   ...
</paths>
```
The path can be absolute `<drive>:\<folder>`, or relative to current directory (as above). So, if you have CasparCG installed in `C:\CasparCG\`, and have `<media-path>` set to `media\`, effective directory is `C:\CasparCG\media\`.
In this case the full directory should be set as Media folder for corresponding playout server (on your third image). 
In redundant configurations (when you have primary and backup server), it may be necessary present the folder as network shared directory `\\server\share\folder`.

**Comment by rifqim** [comment]
Ah, i see.
I already set media-path as you explain to me, use absolute path. The video in Rundown section can be played now.

Thanks for your assistance, Jaskie.
