### ISSUE TITLE
Doubts and Satisfaction on the server

### ISSUE THREAD

**Issue by carloshbranches** [jaskie/PlayoutAutomation#49]
Hello!
I am Brazilian and I was looking for a server that would allow a solution for community television broadcaster. And I am fully convinced that this server meets the criteria of this nature. So congratulations to the server solution!
However, I'm wondering if this play-out server has the ability to display **Closed Captions** **embedded in the XDCAM clip**. Overall, the playout-server meets my needs, Congratulations!

greetings,

**Comment by jaskie** [comment]
Hi,
it's true that CC are not forwarded through CasparCG, as only visible lines are transferred (and mixed inside). SD CC using EIA-608 uses line 21 is not therefore transferred. In HD, the state is more complex - they are present only in MPEG transport stream.
They probably can be converted to another stream in mov files that are played in TVPlay, decoded and transferred to CasparCG output, however we had no such needs yet.

**Comment by jaskie** [comment]
And thanks for appreciation :-)
