### ISSUE TITLE
Logo insertion 

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#5]
How can i import logo into the tvplay application. 

There are three logo option available in application.

Regards,

Fahad

**Comment by jaskie** [comment]
In current binary version it can be done only via manually placing the (png, tif etc) files in PGM media directory. Then you can verify such file in application (on Media tab), and use them. In source code (next binary release) version it can be done via ingest folder...
Mind that logo should have same resolution as channel. And, of course, alpha (transparency).
Kind regards,
Jurek

**Comment by sfahadshahzad** [comment]
Can i use png sequence  for animated logo

**Comment by jaskie** [comment]
No,
animations in CasparCG should be created in different way: as Flash (or -from 2.0.7 server version- in html, js and css) templates. Creating templates is well documented on CasparCG pages.
However, the template support in PlayoutAutomation is not finished yet. I’ll will work on it not earlier as in next week.
It’s also possible to play semi-transparent movie on top layer, but it’s not convenient way and - again - not supported in PlayoutAutomation (and I don’t plan to support it). It can be done externally, i.e. via CasparCGClient.
We use flash template, but it’s controlled via GPI interface (implementing IGpi.cs).
Regards,
Jurek
