### ISSUE TITLE
No output on Blackmagic SDI 4K card

### ISSUE THREAD

**Issue by primozkikelj** [jaskie/PlayoutAutomation#50]
Hello!

My name is Primoz, I am a technical operator on a small TV station, based in Slovenia. Due to all problems we had with commercial playout software, we decided to go open source with CasparCg. Our current configuration is WIN10, i7-8700K. 16GB of RAM, 10TB RAID and Blackmagic SDI 4K video card. We tried official CasparCG server&client, configured in and everything works fine, we get video&audio on the output. Due to limitations of official client, we discoverd your client, but we have some issues. In no way we can not get video&audio on the output, regardless following your installation and configuration manual. 
![Pic_1](https://user-images.githubusercontent.com/48184834/54193504-85bef180-44ba-11e9-85cd-68797e5da74e.JPG)
![Pic_2](https://user-images.githubusercontent.com/48184834/54193509-89527880-44ba-11e9-9fa8-6e5b09374c5d.JPG)
![Pic_3](https://user-images.githubusercontent.com/48184834/54193515-8b1c3c00-44ba-11e9-8c5b-b4f1f34d0e5c.JPG)
![Pic_4](https://user-images.githubusercontent.com/48184834/54193518-8c4d6900-44ba-11e9-846e-e558799c49d3.JPG)

Here is the config file:
https://app.box.com/s/yp0yohrffucnjfcxxrnm39csh67w80ig

Could you please so kind to help us, what are we doing wrong? Please see the attached pics of configuration.

Thanks in advance!

Regards, Primoz

**Comment by jaskie** [comment]
Hi,
it's probably due to invalid media directory path "Media folder" which must point to CasparCG `media` directory.
And also note that engine must specify different primary and backup channels. And preview will cover the programming. So define another channel (i.e with NDI output) for preview in CasparCG, and use it as preview.

**Comment by primozkikelj** [comment]
Hi, thank you very much for your answer. We did so, and got the video and audio output. Thanks again..

Regards,

Primoz
