### ISSUE TITLE
Unable to use Custom command

### ISSUE THREAD

**Issue by btsavb** [jaskie/PlayoutAutomation#51]
Hello,
First, Jaskie, thanks for your work!
I'work in a school for TV technician and we are testing Casparcg and Tvplay.
Probably it's no an issue and i just don't find the way to use it.
I can't validate a custom command
![Capture](https://user-images.githubusercontent.com/48711113/54590421-5c591500-4a28-11e9-8b41-ba2063ab334f.PNG)
The command box is allways in red.
Thanks for your help.

**Comment by jaskie** [comment]
You have to replace channel-layer part with one of [Videolayer](https://github.com/jaskie/PlayoutAutomation/blob/1298affb6acb56be01a52d3d96c4ad3dd682f8a4/TAS.Common/Enums.cs#L67) enum values, i.e.
`PLAY CG3 LOGO`
TVPlay needs to provide the channel using its configuration to both (primary and secondary) servers, so it internally replaces layer name with correct channel/layer and sends the command to relevant server.
Kind regards,
Jurek

**Comment by btsavb** [comment]
Hello, 
Is there a special syntax to play a cutom command like: 
PLAY CG1 DECKLINK DEVICE 1 FORMAT 1080i5000 


The idea is to play the Decklink Input in a Live Event using script 


Thanks 




----- Mail original -----

De: "Jerzy Jaśkiewicz" <notifications@github.com> 
À: "jaskie/PlayoutAutomation" <PlayoutAutomation@noreply.github.com> 
Cc: "btsavb" <support@audiovisuel-cassin.com>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 19 Mars 2019 10:50:46 
Objet : Re: [jaskie/PlayoutAutomation] Unable to use Custom command (#51) 


You have to replace channel-layer part with one of Videolayer enum values, i.e. 
PLAY CG3 LOGO 
TVPlay needs to provide the channel using its configuration to both (primary and secondary) servers, so it internally replaces layer name with correct channel/layer and sends the command to relevant server. 
Kind regards, 
Jurek 
— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 


-- 


Philippe Martin 
Support technique 


Lycée René Cassin 
Pôle Image et Son 
tél : 05 59 63 97 07 
9 rue Jules Ferry 
64200 Biarritz

**Comment by jaskie** [comment]
A rundown item of Live type is intended to play live source on program layer. You can use this with PLAY `DECKLINK DEVICE 1 FORMAT 1080i5000` set as Live device name in TVPlay.config. However, it does not allow to play other decklinks, what would be possible using the custom command attached to the live event. Unfortunately, bug exists in code that forwards the command to CasparCG and the command is clipped. I'll fix it and publish new binaries ASAP.

**Comment by btsavb** [comment]
it works 
thank you 
have a nice week end 

----- Mail original -----

De: "Jerzy Jaśkiewicz" <notifications@github.com> 
À: "jaskie/PlayoutAutomation" <PlayoutAutomation@noreply.github.com> 
Cc: "btsavb" <support@audiovisuel-cassin.com>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 22 Mars 2019 13:51:35 
Objet : Re: [jaskie/PlayoutAutomation] Unable to use Custom command (#51) 


A rundown item of Live type is intended to play live source on program layer. You can use this with PLAY DECKLINK DEVICE 1 FORMAT 1080i5000 set as Live device name in TVPlay.config. However, it does not allow to play other decklinks, what would be possible using the custom command attached to the live event. Unfortunately, bug exists in code that forwards the command to CasparCG and the command is clipped. I'll fix it and publish new binaries ASAP. 
— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 


-- 


Philippe Martin 
Support technique 


Lycée René Cassin 
Pôle Image et Son 
tél : 05 59 63 97 07 
9 rue Jules Ferry 
64200 Biarritz

**Comment by jaskie** [comment]
Fixed in ec4c46b4b041019d61af17a80225b8ac4890c072.
