### ISSUE TITLE
Difficulty connecting to TVPLAY Client

### ISSUE THREAD

**Issue by carloshbranches** [jaskie/PlayoutAutomation#52]
Hi!
I had commented a few weeks ago about the satisfaction of the playout resources for the community broadcaster that I am part of. Since now, I've noticed a playout feature, which is redundancy, through the wiki and in the issues.
For the switcher control room, we look for a possibility of having two machines: the primary displaying the materials; and a second one for playlist operation and media import. This facilitates the work of the operators.
 The redundancy feature we chose is the TV Play Client. However we are having difficulty connecting from the TV Play Client to the server.
We have already set the tcp free port number on the Rundown Engines tab in TVPLAY config and turn on the TV PlaySvc.exe, and when we request signal recognition on other computers, it does not connect to the server. We tried other ports but the problem persists.
We have also mirrored the database in the database configuration.

I am sending the prints for better visualization of the reported problem.

![1](https://user-images.githubusercontent.com/48390521/54875627-32657100-4de1-11e9-9b3b-e543aaea1a93.png)

![2](https://user-images.githubusercontent.com/48390521/54875477-e5809b00-4dde-11e9-90d8-2887b0ed88b6.png)

![3](https://user-images.githubusercontent.com/48390521/54875482-f7fad480-4dde-11e9-94af-c181701296c1.png)

For better understanding of the case, the main computer for display is the ip 192.168.1.11 which is the server; and another secondary computer for media operation is ip 192.168.1.40;
I believe that the Firewall is related to this question, but already allowed connection of the ports between the computers

What other detail might we forget to set up for this connection to work?

**Comment by jaskie** [comment]
You also have to add the client's IP address to allowed users in main TVPlay.exe application. It may be the case.
There is simple client rights management, currently based only on client IP address. The rights itself may be assigned at engine and rundown container levels.

**Comment by carloshbranches** [comment]
Hi!
Got it. Thank you very much for that remark.
It worked!
As I've been using two computers, database errors have occurred, in the alarm in the lower left corner. It may be the redundancy conflict in the database since it is mirrored.

Also, I have another subject to discuss as to the buffer preview, the play timecode does not match the original timecode of the media. For example, the video delays 1 second to get started. This occurs at the time of material trimming.
Is this because of the fact that the frame rate of the channel is not the same as the frame rate video?
We are currently working with the 1080i5994 format channel on the PREVIEW channel. The material used in ingest is XDCAM with frame rate 29.97. What can be done about it?

greetings,

**Comment by jaskie** [comment]
Hi,
regarding the database error: It occurs, if two instances of TVPlay/TVPlaySvc are working simultaneously. For redundancy, the backup one should be started when main isn't operating in database. For some rundowns, if TVPlay's window is closed, the application continues to write data to database for several seconds (every event with changed i.e. start time is saved). Just synchronize the databases, and run the backup instance only in state of failure.

The second issue: there is probably a bug in NTSC framerates support, as they are not tested well enough. Please, provide me a sample media file with relevant data that will allow to reproduce the case easily.

**Comment by carloshbranches** [comment]
Hi,
1. So, using the client without TVPlaySvc running, this error should not happen, right?
*
As for the problem of video trimming
I'm submitting two prepared sample materials in the same way I've prepared other videos set to display in schedule grid. If you do not prefer the xDCAM format just because of the file size and also for the comparison, you can download the MOV that will be sent.

The video sample XDCAM FORMAT has the following information:
codec: XDCAM HD 50 NTSC 4:2:2
Wrapper Type: MXF OP1a
format: XDCAM mxf
image size: 1920 x 1080 px
Frame rate 29.97
Source audio format: 48000 Hz - 24-bit - 8 channels
Audio format of the project: 48000 Hz - 32-bit floating point - 8 channels
Total duration: 00; 00; 39; 01
Pixel aspect ratio: 1.0

QUICKTIME FORMAT
codec: H.264
Type: MPEG Movie
Image Size: 1920 x 1080
Frame rate: 29,97
Source Audio Format: 48000 Hz - Compressed - Stereo
Project audio format: 48000 Hz - 32-bit floating point - Stereo
Total duration: 00; 00; 39; 01
Pixel aspect ratio: 1.0

NOTE: Both videos respect the XDCAM standard material delivery model with the following structure:
* 5s clapper board (white background to confirm clapper time)
* fade of 2s
* material content of 30s
* final fade of 2s

The part of the video trimmed logically will be the material content.
I sent the material in this way, because some producers, by default, deliver the materials in this way.

download links

[XDCAM](https://www.4shared.com/file/ujcgxOBzda/SAMPLE_VIDEO.html)


[QUICKTIME](https://www.4shared.com/video/dA6HatHdgm/SAMPLE_VIDEO_QUICKTIME.html)


greetings, and
Thanks for the assistance!

**Comment by jaskie** [comment]
Hi,
I just released fixes that allows properly ingest and preview NTSC-based-framerate content. Please, check if I'm right.
Regarding TVPlaySvc: it's the TVPlay without user interface, so only way to use it is the TVPlayClient. Because it also connects to databases(s), it should not be started simultaneously with TVPlay. Maybe I should limit concurrent database connections internally in database, but I think any malfunction of the limitation may be risky to actual programming.
-- Jurek

**Comment by carloshbranches** [comment]
Hi,

I checked here and I trim the video, but in the primary output, when I play, the cut out misaligned. This is noticeable when the black screen appears after the video. Maybe it's normal NTSC defect itself.
In my configuration, the CasparCG channels and also the TV PLAY (in Rundown Engines) are of 1080p2997 format.
What is the format setting of the channels you used during the fixes?

grettings,

**Comment by jaskie** [comment]
Hi,
if the difference is 1-2 frames, it may be hard to overcome. IMHO our CasparCG fork seeks files very precisely, however it's worth checking if frame number calculation is correct. I'll do this.
What I tested was 1080i5994.
--- Jurek

**Comment by carloshbranches** [comment]
Hi,
Good that the difference is 5 frames. Also, when I pause the video and copy the TC and play again in preview, the video delays more frames, which is noticeable at the end of the clip.
Above all, thank you very much for the assistance and support!
Other than that, the playout satisfies us with all its resources.
Congratulations on the playout solution!

best regards,
