### ISSUE TITLE
Cant we get UDP/RTP stream out from player

### ISSUE THREAD

**Issue by sachin0606** [jaskie/PlayoutAutomation#53]
Hi, 

Thanks for the source and wanted to know new feature which can make the player more flexible. the output of the player cant br directly stream as UDP/RTP stream so can directly insert in our device without the decklink card.

**Comment by jaskie** [comment]
Hi,
the actual output is produced by [CasparCG](https://github.com/CasparCG/) server - this is media player. We use our (public) [fork of the CasparCG](https://github.com/jaskie/Server) that is able to produce decent UDP (uni- and muticast) stream. RTMP (used i.e. by YouTube) is working OK as well. RTP support is unknown to me - however the possibilities should be equal to bare FFMpeg which is used by CasparCG internally.

**Comment by sachin0606** [comment]
Thanks for the quick response. one more question. CasperCG is required OPENGL. anyway to work arournd with old graphics card with OPENGL 1.1 support?

**Comment by jaskie** [comment]
Yes, using software mixer on CasparCG 2.2. I was tested it once (at beta stage), but it was not complete enough to use, however many fixes was applied since then.
I'm also thinking about CasparCG alternative: it may be a [OBS Studio](https://obsproject.com/) or something other FFMpeg-based.

**Comment by sachin0606** [comment]
unable to install the CasparCG  due to lack of support OPENGL.

**Comment by jaskie** [comment]
Indeed, I just looked at CasparCG 2.2 release, and it seems not to support CPU mixer at all. You have to buy a GPU (a cheapest GTX 710 is enough for single HD channel).

**Comment by sachin0606** [comment]
Yes. i gonna buy that now and confirm you. But thanks for quick response and great code.
