### ISSUE TITLE
configuration engine error

### ISSUE THREAD

**Issue by burakguder** [jaskie/PlayoutAutomation#54]
![error_config](https://user-images.githubusercontent.com/560147/61123078-167afd80-a4ac-11e9-8f7b-78e82653ad9f.png)

the system i use windows 10

I get the same error no matter what I do.  ( Command failed. Following error occurred: Fatal error encountered during command execution  )

I can't solve the problem I'm waiting for your help

![error_config](https://user-images.githubusercontent.com/560147/61123715-be44fb00-a4ad-11e9-9e3b-c2381c7aff7a.png)
![error_config2](https://user-images.githubusercontent.com/560147/61123716-be44fb00-a4ad-11e9-83a6-32984826d17c.png)
![error_config3](https://user-images.githubusercontent.com/560147/61123717-be44fb00-a4ad-11e9-8c94-4ce248396431.png)
![error_config4](https://user-images.githubusercontent.com/560147/61123719-bedd9180-a4ad-11e9-85f2-f2171a4a23b7.png)
![error_config5](https://user-images.githubusercontent.com/560147/61123721-bedd9180-a4ad-11e9-8bb1-e672a30a8b39.png)
![error_config6](https://user-images.githubusercontent.com/560147/61123722-bedd9180-a4ad-11e9-931e-de626b643b94.png)
![error_config7](https://user-images.githubusercontent.com/560147/61123723-bedd9180-a4ad-11e9-94e1-db95cbb69013.png)
![error_config8](https://user-images.githubusercontent.com/560147/61123724-bf762800-a4ad-11e9-8a1b-2767ef7abfe7.png)

**Comment by jaskie** [comment]
Which is MySql version? It looks that there is a problem with saving to database.

**Comment by jaskie** [comment]
BTW, there are misunderstandings in your configuration:
First, the TVPlayClient is an application that connects to a running instance of TVPlay.exe (not to CasparCG) and allows multi-user operation.
Next, channels in CasparCG are numbered starting from 1, so the channel number have to be 1 or more.
Third, reference loudness is the loudness level according to EBU R.128 recommendation, and can't be zero. The recommended default is -23 LUFS.

**Comment by jaskie** [comment]
I just tested with most recent MySql server, without errors. However, your connection string looks strange to me as SSL mode isn't shown, can you ensure that you are using most [recent version of binaries](https://github.com/jaskie/PlayoutAutomation/releases/latest)?
If yes, I'll build newer version that will show some more details.

**Comment by burakguder** [comment]
I downloaded and installed the version you say  , now worked but tv client not working.

How to edit playlist stream :( 

![error](https://user-images.githubusercontent.com/560147/61170301-17756300-a570-11e9-9671-3314505e62ba.png)
![error2](https://user-images.githubusercontent.com/560147/61170302-17756300-a570-11e9-8ead-37f5da7ee2ca.png)

**Comment by burakguder** [comment]
Is there a detailed user manual of the program ? I want to learn how to add html5 templates, add logo, categorize.

**Comment by burakguder** [comment]
To add a logo, I can't find the field  
I also couldn't see where to add flash or html template

![error10](https://user-images.githubusercontent.com/560147/61177282-124cfe00-a5da-11e9-904b-22e3e122f4a8.png)

**Comment by jaskie** [comment]
That's fine that you made it work.
There is no ultimate guide of usage and configuration, only [wiki](https://github.com/jaskie/PlayoutAutomation/wiki).
The TVPlayClient: it connects to TVPlay, not to CasparCG. Threfore you have to:
- enable it in TVPlay.config, on Engines tab, at bottom of the form: Enable remote control interface and assign a free TCP port to it (I usually use 1060, 1061 etc). Start TVPlay and check if no errors were logged (current date log file in logs folder), especially about port was already used. 
- If all is OK, go to menu Tools->User manager and create a user with admin rights, using "station IP address" as authentication source, and actual PC running TVPlayClient IP address as authenticating object.

Now you can start TVPlayClient on the machine which IP address you specified. Don't forget to open firewall port for the service. If still not working, see program's log files.

Regarding logo control: refer to [this part](https://github.com/jaskie/PlayoutAutomation/wiki/Plugins) of wiki.

**Comment by burakguder** [comment]
sorry for asking so many questions :(  I followed the instruction and menus opened  but I get an error 
![error12](https://user-images.githubusercontent.com/560147/61177500-ad94a200-a5df-11e9-8ed6-35e183bd2b2c.png)

**Comment by jaskie** [comment]
Ok, you need to place the graphics in CasparCG media folder. He complains that didn't found any "P18" file. It may be, i.e., `p18.png` of resolution equal to CasparCG channel it will be playing on, and transparency (alpha) channel.
Take a look at [AMCP protocol](https://github.com/CasparCG/help/wiki/AMCP-Protocol) - it's easy to determine which command CasparCG received (in your case it was `LOADBG 1-21 P18 MIX 25`) resulted an error.

**Comment by burakguder** [comment]
I will do what you say 

another question,  i couldn't find  html5 template for video

**Comment by jaskie** [comment]
We do not use html templates. 
You can make its own, but they must be run on CasparCG 2.07 or 2.2. Our fork is based on 2.06. The reasons for our fork are described on beginning of its [readme.txt](https://github.com/jaskie/Server/blob/master/README.txt) file, so you can decide.
Flash template example (a crawl ticker) is [here](https://github.com/jaskie/TVPlayCasparCgTemplates).
