### ISSUE TITLE
Big issues with audio clicks and pops no compatibility with CCG2.1

### ISSUE THREAD

**Issue by mindandvision** [jaskie/PlayoutAutomation#55]
Hi,

I cannot get TVPlay to work without problems with my machine (Decklink SDI). 
The issue is related to the old CCG version that comes with TVPlay. If I use it, I get nothig but clicks and pops inside the audio (I use system audio with Dante Virtual Soundcard). 

This issue only occurs with your CCG version. If I use the official 2.1 version of CCG (which I really would want to use anyway because of some other features) the issue is gone and audio is crytsal-clear.

Unfortunately the CCG 2.1 version doesn't work with your TVPlay because it throws out errors when trying to play a clip. It seems that the command structure was changed with 2.1.

Any solution to this?

Thanks in advance for your help!

pro

**Comment by jaskie** [comment]
Hi,
both issues should be fixed.
1. Provide me your casparcg.config to replicate issue.
2. Check with [CasparCG 2.2](https://github.com/CasparCG/server/releases) and confirm the issue still exists, provide a error sample.
BTW, why you don't use Decklink embedded audio? You should, as system audio is not in sync with Decklink's video in general. 
If you are streaming somewhere, it would be better to use another output (UDP mpegts, rtmp or NDI).

**Comment by mindandvision** [comment]
Hi Jaskie,

thanks for the quick reply! Great support!

I found the issue - it was a Windows update that messed up the network settings for the Dante Network Card. It did that without any warning or whatever. But I found the messed up setting and now it's working again.

I need the Dante connection for a special purpose - so embedded playout is not an option here. There are no syncing issues as I can correct this with delays. It works perfect.

The other issue is with CCG 2.1. You mentioned CCG 2.2 which is unfortunately not an option for me because I need the PSD producer that was removed in 2.2.

The error comes with the Play command. TVPlay sends something like "Play 1-16" and CCG says that this command isn't understood. Unfortunately I'm not at the specific machine at the moment. I will copy the precise error message tomorrow, when I can work at the machine again. Then I will provide the CCG config too.

Thanks for all your help!

pro

**Comment by mindandvision** [comment]
OK here is the error with CCG 2.1:

```
[2019-07-17 12:03:37.673] [4648]  [info]    Received message from 127.0.0.1: PLAY 1-16\r\n
[2019-07-17 12:03:37.679] [4648]  [info]    Received message from 127.0.0.1: MIXER 1-16 VOLUME 0.3548134 10 LINEAR\r\n
[2019-07-17 12:03:37.748] [9700]  [error]   No match found for supplied commands. Check syntax. Turn on log level debug for stacktrace.
```

Another question: How do I use the XKeys Plugin? I copied it into the plugins folder but nothing happens. I cannot control TVPlay with an attached x-24 keyboard. What do I do wrong here?

Thanks!

pro

**Comment by jaskie** [comment]
No, the error probably does not refer to these commands. It's probably is little late, and refers to LOADBG command earlier. But try to execute them manually from console, you'll know for sure.
XKeys plugin: did you copied the plugin to plugins folder, set engine name and unit Id in XKeys.xml configuration file properly? Then check log file for errors regarding the plugin.

**Comment by mindandvision** [comment]
What is the Engine Name? The name of the Rundown Engine that I configured in the Comfiguration Program?

**Comment by mindandvision** [comment]
I don't have any luck with the XKeys Plugin. Only if I set the UnitID to "0" in the xml file the XKey Keyboard changes some backlight color but I can't control anything. If I set it to the right UnitID nothing happens at all.

**Comment by mindandvision** [comment]
OK found the problem: The XKeys Keyboard had a wrong PID:

`13:37:04.7449|TAS.Client.XKeys.Device|ERROR|Invalid XKeys device PID mode: 1027, should be 1029 (mode 1)`

Changed it to 1029 - now it seems to work.

**Comment by sfahadshahzad** [comment]
> 
> 
> OK found the problem: The XKeys Keyboard had a wrong PID:
> 
> `13:37:04.7449|TAS.Client.XKeys.Device|ERROR|Invalid XKeys device PID mode: 1027, should be 1029 (mode 1)`
> 
> Changed it to 1029 - now it seems to work.

@mindandvision I am using too old version of X-Keys device which is X-Keys Professional SE and unable to change PID, can you please tell me how do i change PID from 657 to 1029.

Thanks

Fahad
