### ISSUE TITLE
How to add ip live stream ?

### ISSUE THREAD

**Issue by burakguder** [jaskie/PlayoutAutomation#56]
(HLS, RTMP, RTSP) How do I add live feeds directly on playout?

**Comment by H0fek** [comment]
"Add next, empty movie" and enter your url in Properties under Name.

**Comment by H0fek** [comment]
I don't think that adding it as a media is possible. Walkaround would be setting your "Live device name" to desired url and then in rundown "add next live". However, that is not so dynamic.

![liveDevice](https://user-images.githubusercontent.com/19623505/61721326-96d11680-ad68-11e9-9fb1-dc61acd3f62f.jpg)

**Comment by jaskie** [comment]
It's somewhat complicated. As every input device requires some time to start-up, playing them directly in CasparCG is not best idea. In fact, only Decklink inputs have the time small enough to be acceptable in some circumstances (it's less than 0.5 second). In this case, enter `DECKLINK 1` as live device name (on picture provided by @H0fek), assuming your input card is the first in order. 
Actual streaming video have to be decoded and provided to Decklink input with other means, i.e. using second Decklink card and [OBS Studio](https://obsproject.com/), or bare FFMpeg (compiled with --enable-decklink).

Other option is to use channel producer in CasparCG. In this case the input will be played constantly on another CasparCG channel (you'll have to setup it in `casparcg.config`), and routed to main CasparCG channel using `route://2` as input name (assuming the additional channel is second channel in casparcg.config) This removes necessity of using two separate Decklinks only to route the signal to CasparCG input.

It was tested and work OK with [NDI](https://www.newtek.com/ndi/) live inputs (as NDI input needs about 6 seconds to show up).

You can also mix two above approaches (that will give you best results): use the additional CasparCG channel, use OBS with Decklink or NDI output. To correctly set-up all, I recommend using CasparCG console. The commands that would be needed would be:
`PLAY 1-0 route://2` - play on channel 1 layer 0 output of channel 2,
`PLAY 2-0 DECKLINK 1` - play on channel 2 layer 0 input of first Decklink card,
`PLAY 2-0 NDI <ndi_source_name>` play on channel 2, layer 0 NDI input of _ndi_source_name_. You can see the name in NDI video monitor's app on its title bar while playing the source.

Both kinds of inputs (NDI or DECKLINK) can be initialized for a channel from `casparcg.config`. Yo can know more about this from [release notes](https://github.com/jaskie/Server/releases).

You may also try with playing streams directly in CasparCG using i.e.
`PLAY 1-0 STREAM "udp://127.0.0.1:56221"` command.

**Comment by vfmradio** [comment]
> You may also try with playing streams directly in CasparCG using i.e.
PLAY 1-0 STREAM "udp://127.0.0.1:56221" command.


Hello! Can anyone tell me why this is not working?
