### ISSUE TITLE
Windows system sounds through SDI

### ISSUE THREAD

**Issue by primozkikelj** [jaskie/PlayoutAutomation#58]
Hello Mr. Jurek!

We are running your TvPlay sw on a small TV station. We have some strange problems with system sounds from Windows playing on SDI output (also clips from YT). Have checked numerous times CasparCG configuration file, and I simply have no idea what I am doing wrong. I've tried official client also, but problem remains the same. Would you be willing to help and check the configuration file?

Thanks in advance!

Regards!

Primož
[casparcg.txt](https://github.com/jaskie/PlayoutAutomation/files/3497556/casparcg.txt)

**Comment by jaskie** [comment]
The reason for this is not on CasparCG side, but it is a feature of Decklink driver. Simply disable Decklink as playback device in windows sound settings.
Kind regards,
Jurek

**Comment by primozkikelj** [comment]
Hello. Mr. Jurek!

Thanks for your answer, I have tried what you have written, but the problem remains the same. I'll try to explain a little bit deeper. If I edit the caspar config file:

channel
        video-mode 1080i5000 /video-mode
        channel-layout stereo /channel-layout
         consumers
           decklink
           **system-audio /system-audio**	
        /consumers>
    /channel

and delete bold line "system audio", I do not get audio on SDI output at all (regardless of enabled/disabled audio devices in windows environment).

If I put that line back, and disable BD as default device, the problem is the same - no audio. If I enable it, audio gets through, but with windows system sounds, chrome. mozilla..etc. 

The solution is to disable windows system sounds and other sounds in windows audio mixer, but I think this is not correct way of solution. 

Any help would be appreciated,

Best regards,

Primož

**Comment by jaskie** [comment]
A, so there is another problem: you deliver audio using Windows sound driver, what is not best method of doing it. Better would be:
- enabling embedded audio for decklink (as is disabled by default),
- remove system-audio, 
- disable Decklink in Windows playback devices.
So your consumer should look like:
```xml
  <decklink>
    <device>1</device>
    <embedded-audio>true</embedded-audio>
    <keyer>default</keyer>
    <latency>normal</latency>
    <buffer-depth>5</buffer-depth>
  </decklink>
```
The `device` and `latency` settings above represent default values, so they may be omitted, but `embedded-audio` defaults to `false` and `buffer-depth` defaults to 3. Larger buffer is better when machine is under stress, but too big may be noticed as command delay. But 5-7 frames is hardly noticeable.
If it helped, please, close the issue.
Kind regards,
Jurek

**Comment by primozkikelj** [comment]
Hi, Mr. Jurek

Thanks again for your answer. It was a completely my mistake. I was configuring consumers in the commented section of caspar config file, in the section marked with ...thanks again for your time and help!

Best regards,

Primož

**Comment by primozkikelj** [comment]
I meant marked with `<!-- -->`..

Thanks!
