### ISSUE TITLE
SCTE-35 support

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#59]
It possible to get SCTE-35 signal with decklink output.

Regards,

Fahad

**Comment by jaskie** [comment]
IMHO not, as [the standard](https://www.scte.org/SCTEDocs/Standards/ANSI_SCTE%2035%202019r1.pdf) operates on compressed streams (MPEG-DASH and HLS), and Decklink outputs non-compressed video.
The relevant US standard seems to be [ANSI/SCTE-104](https://www.scte.org/SCTEDocs/Standards/ANSI_SCTE104%202017.pdf) and it can be implemented in TVPlay as a engine plugin. However, it's not in our schedule.
Kind redards,
Jurek
