### ISSUE TITLE
Simultaneous output on SDI and ipstream

### ISSUE THREAD

**Issue by primozkikelj** [jaskie/PlayoutAutomation#60]
Hello Mr. Jurek!

We are using your sw and would like to send output to SDI on Blackmagic SDI 4K and ipstream. We are planning to add a second NIC. We would like to have a CBR of 5Mb/s. Is that possible, I mean just to add a few extra lines to casparcg config file? Thank you very much for your answer!

Best regards,

Primož

**Comment by jaskie** [comment]
Hi Primož,
yes, it's relatively easy. Check out [this wiki page](https://github.com/jaskie/Server/wiki/Creating-perfectly-stable-CBR-MPEG-transport-stream) - there are some working configurations. It's up to you whether you need a solid stable stream bitrate or not, but there are examples for both configurations.
Kind regards,
Jurek
