### ISSUE TITLE
XKeys universal plugin

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#64]
Hi,

I know that TVPlay only support XK-24 but i would be great if it support other models.

I am trying to attach my X-Keys Professional SE with 58 Keys and getting error.

21:53:12.9532|TAS.Client.XKeys.Device|ERROR|This plugin does not support the Xkeys device 
21:53:12.9612|TAS.Client.XKeys.DeviceEnumerator|INFO|New device connected 657:1523 

Regards,

Fahad

**Comment by jaskie** [comment]
Hi,
I need you to collaborate: here you have TVPlay develop binaries with the plugin without actual device checking. If you confirm that it's working properly, I'll include the device in releases. You may need to upgrade database schema (using TVPlay.Config.exe's check connection button).
Kind regards,
Jurek
[TVPlay.zip](https://github.com/jaskie/PlayoutAutomation/files/3851973/TVPlay.zip)

**Comment by sfahadshahzad** [comment]
I think the device which i am using it is too old and was previously used with GIZMO plugin with Vizrt.

I tried to update the PID from 657 to 1029 but no luck because the pid is not editable with macroworks.

Regards,

Fahad

**Comment by jaskie** [comment]
It seems that it uses legacy SDK, so there is not possible to use it using exactly same code. I think only way to support it is to have it on desk.
There will be another model supported this year, as we just ordered [XK-12 Jog and Shuttle](https://xkeys.com/xk12jsh.html) and I'll write code for it.
