### ISSUE TITLE
Table tas.RunDownEvent doesn´t exist

### ISSUE THREAD

**Issue by cooliobr** [jaskie/PlayoutAutomation#69]
How I can fix this error?
PS.: my data base is on a Linux Server ( Mariadb Server version: 10.1.37-MariaDB-0+deb9u1 Debian 9.6 )
Playout is a Windows 10 machine.
```
MariaDB [tas]> show tables;
+------------------------+
| Tables_in_tas          |
+------------------------+
| aco                    |
| archive                |
| archivemedia           |
| asrunlog               |
| customcommand          |
| engine                 |
| engine_acl             |
| media_templated        |
| mediasegments          |
| params                 |
| rundownevent           |
| rundownevent_acl       |
| rundownevent_templated |
| server                 |
| servermedia            |
+------------------------+
15 rows in set (0.00 sec)

MariaDB [tas]> 

```

**Comment by jaskie** [comment]
It's *feature* of MariaDB on Linux system - [identifier name case-sensitivity](https://mariadb.com/kb/en/library/identifier-case-sensitivity/), which is enabled by default on Linux systems. You can change it as described in the link.
However, these inconsistent table names comes from TVPlay's source code, which will be fixed as well.
Thanks for reporting,
Jurek

**Comment by cooliobr** [comment]
thanks for your faster reply.
sorry for my poor english.
you have any read-me or how-to for how add media files on rundown?

**Comment by jaskie** [comment]
It's just the [wiki](https://github.com/jaskie/PlayoutAutomation/wiki)
