### ISSUE TITLE
AsRunlog incorrect time

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#7]
Mysql database time is in correct; When i place some files in rundown and execute play command it show me wrong time.

how do i correct time in databse ?

**Comment by jaskie** [comment]
Database times are in UTC. Is that Ok?

Mysql database time is in correct; When i place some files in rundown and execute play command it show me wrong time.

how do i correct time in databse ?

**Comment by jaskie** [comment]
@sfahadshahzad 
did my response (that database time is in UTC) answered you question?
Kind regards
Jurek
