### ISSUE TITLE
Can't Ingest Clips

### ISSUE THREAD

**Issue by lawesw** [jaskie/PlayoutAutomation#72]
Hi, I'm trying to ingest clips into the playout but i keep getting this error.

"5/04/2020 12:36:27 PM Object reference not set to an instance of an object."

**Comment by jaskie** [comment]
Hi,
at first sight it look like your engine does not have properly configured primary playout channel.

1. Setup a server with media directory pointing to CasparCG media folder,
2. Add a channel to the server (note that they are numbered from 1 upwards),
3. Set the channel as primary in engine config.

Was I right? If not, describe something more.

**Comment by lawesw** [comment]
Thanks for your response,
I have made those changes, I am now getting this error

"5/04/2020 11:42:38 PM Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height"

**Comment by jaskie** [comment]
The ingest operation uses [FFMpeg](http://ffmpeg.org/) to transcode/rewrap source file during ingest. This error may be caused by unsupported/invalid ingest folder configuration, ie. using NVENC encoder while it's not available in system. To further diagnose this, more FFMpeg output is then required. From TVPlay's user interface it's visible using cog icon near progressbar of each ingest operation. There you can check the command that's executed, and more FFMpeg messages.
You can paste the messages here, I'll help. Your actual ingest folder configuration will be useful as well.

**Comment by lawesw** [comment]
Ingest now seems to be working, thanks! Having the ingest config set to NVENC was causing the issue, I changed it back to copy and its now working. One last thing.. Is there a way to either play-out over NDI or live stream to a server?

**Comment by jaskie** [comment]
I would recommend using libx264 or mpeg2video as video codec, if files are form different, uncertain sources. This will ensure that files are playable. It will also allow some video conversions during ingest.
Regarding live stream play-out, refer to [FAQ](/jaskie/PlayoutAutomation/wiki/Faq)

**Comment by susedx** [comment]
Hello,

I have similar issue, I am getting error log below, when trying ingest a file. Channel in server config has just this configuration, is it correct?

```
  <channels>
    <channel>
      <video-mode>720p29.976</video-mode>
      <channel-layout>stereo</channel-layout>
      <consumers>
          <screen />
<!--
          <decklink>
            <device>1</device>
            <embedded-audio>true</embedded-audio>
            <keyer>default</keyer>
            <latency>normal</latency>
            <buffer-depth>4</buffer-depth>
          </decklink>
          <ndi>
            <name>TEST</name>
            <blocking>true</blocking>
          </ndi>
-->
      </consumers>
    </channel>

  </channels>
```

log from ingesting:

7/30/2021 12:37:09 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:09 PM Object reference not set to an instance of an object.
7/30/2021 12:37:09 PM Object reference not set to an instance of an object.
7/30/2021 12:37:10 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:10 PM Object reference not set to an instance of an object.
7/30/2021 12:37:10 PM Object reference not set to an instance of an object.
7/30/2021 12:37:10 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:10 PM Object reference not set to an instance of an object.
7/30/2021 12:37:10 PM Object reference not set to an instance of an object.
7/30/2021 12:37:11 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:11 PM Object reference not set to an instance of an object.
7/30/2021 12:37:11 PM Object reference not set to an instance of an object.
7/30/2021 12:37:11 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:11 PM Object reference not set to an instance of an object.
7/30/2021 12:37:11 PM Object reference not set to an instance of an object.
7/30/2021 12:37:12 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:12 PM Object reference not set to an instance of an object.
7/30/2021 12:37:12 PM Object reference not set to an instance of an object.
7/30/2021 12:37:12 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:12 PM Object reference not set to an instance of an object.
7/30/2021 12:37:12 PM Object reference not set to an instance of an object.
7/30/2021 12:37:13 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:13 PM Object reference not set to an instance of an object.
7/30/2021 12:37:13 PM Object reference not set to an instance of an object.
7/30/2021 12:37:13 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:13 PM Object reference not set to an instance of an object.
7/30/2021 12:37:13 PM Object reference not set to an instance of an object.
7/30/2021 12:37:14 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:14 PM Object reference not set to an instance of an object.
7/30/2021 12:37:14 PM Object reference not set to an instance of an object.
7/30/2021 12:37:14 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:14 PM Object reference not set to an instance of an object.
7/30/2021 12:37:14 PM Object reference not set to an instance of an object.
7/30/2021 12:37:15 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:15 PM Object reference not set to an instance of an object.
7/30/2021 12:37:15 PM Object reference not set to an instance of an object.
7/30/2021 12:37:15 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:15 PM Object reference not set to an instance of an object.
7/30/2021 12:37:15 PM Object reference not set to an instance of an object.
7/30/2021 12:37:16 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:16 PM Object reference not set to an instance of an object.
7/30/2021 12:37:16 PM Object reference not set to an instance of an object.
7/30/2021 12:37:16 PM Operation started: Ingest Ingest:\mateChannel -> :mateChannel
7/30/2021 12:37:16 PM Object reference not set to an instance of an object.
7/30/2021 12:37:16 PM Object reference not set to an instance of an object.
```
