### ISSUE TITLE
TvPlay Remote crash.

### ISSUE THREAD

**Issue by theusmpa** [jaskie/PlayoutAutomation#76]
Hello good afternoon!

I found a problem in the last version made available, I believe it is a possible bug, in the remote client application when manipulating a media to make the entry and exit markings, in the "Rundown" tab and in the "Media" tab, the application crashes, when viewing in the Windows task manager notices a strange behavior, it starts to consume all the memory of the machine.
Is this behavior known to you?

Any solution?

Thank you.

Matheus

**Comment by jaskie** [comment]
Would you confirm, that in current release it still happens? I didn't reproduced it, however not tested on previous release, so it may happen under some specific circumstances.
-- Jurek

**Comment by theusmpa** [comment]
After your last commit (about that problem of saving users' security settings), still don't test it, I'll do it on Monday.

I will give feedback, thank you.

Matheus

**Comment by theusmpa** [comment]
Confirmed, unfortunately the latest version still continues with the instability mentioned above.

Here when playing the file in the preview, after stopping the client stops responding.

tks

--Matheus

**Comment by theusmpa** [comment]
I left some time to see if it normalized, it gets to lock the machine due to memory overflow .... see:

![memoria](https://user-images.githubusercontent.com/6371447/86037285-8237dc80-ba15-11ea-901a-f8e632ebcc78.png)


Thank you.

--Matheus

**Comment by jaskie** [comment]
Release is updated to version 1.7.7489
