### ISSUE TITLE
Recording channel

### ISSUE THREAD

**Issue by theusmpa** [jaskie/PlayoutAutomation#78]
Hello good afternoon!

Please, could you clarify how to correctly configure a recording channel in the application?

I did not succeed in my attempts!

I'm using the Caspar CG TvPlay fork.

Thank you!

**Comment by jaskie** [comment]
First, you have to add recorder to CasparCG configuration. It's possible only for Decklink input. It's sample is in commented part of `casparcg.config` file:
```xml
<recorders>
    <decklink>
      <device>2</device>    - decklink device to connect to control VTR
      <preroll>1</preroll>  - tape preroll, in seconds
      <offset>2</offset>    - capture offset, in frames
    </decklink>
</recorders>
```
You have to add this regardless of using or not the VTR control. Such recorder allow to capture from VTR as well as do "crash recording" - start and stop it manually. It's described in [wiki](https://github.com/jaskie/Server/wiki/Deck-control-(recorder)).

Second, you have to define recorder(s) on _Playout servers_ window of TVPlay.config.exe. Recorder Id is its number in `casparcg.config` file, so first defined recorder will have Id = 1. You can set default channel number to record from, but it's optional.

Then you'll have "Record" tab on media page in TVPlay. If you have no VTR, crash recording should be still possible. Let me know about your mileage, as I never tested it on NTSC-framerate channels.

**Comment by jaskie** [comment]
I assume the explanation is ok, closing issue.
