### ISSUE TITLE
User permission

### ISSUE THREAD

**Issue by theusmpa** [jaskie/PlayoutAutomation#79]
Hello good afternoon!

I am configuring a user, basically to allow access through the remote application, but every time I closed and opened the server, I lose the administrator's permission for that user, I have to redo this permission setting, because otherwise the remote application cannot operate at list.

Could you please check why this configuration is not being saved?

Thank you!

**Comment by jaskie** [comment]
It's a bug, it was fixed in c606467789508962d301305a76035679cf93b8b9, after binary release. I'll compile and publish update tomorrow.

**Comment by theusmpa** [comment]
ok, thanks

**Comment by jaskie** [comment]
Just released 1.7.7476
