### ISSUE TITLE
Backup Instance

### ISSUE THREAD

**Issue by theusmpa** [jaskie/PlayoutAutomation#80]
Jackie, good afternoon!

I would like to give a suggestion, I believe it could be easy to implement and would bring great operational gains.

In the topology I am thinking of using TvPlay, I will need everything redundant, that is, casparCG and the TvPlay application, in addition to making remote access with customers.

It turns out that when I run a backup instance of the TvPlay server, the rundown is not updated in both instances, so in a situation that needs to trigger the backup immediately, the operator will have to redo the entire script in the rundown.

If it were possible to keep the rundown updated between the two instances and to ensure that the CCG does not receive double commands, it would put a button that by default would be invisible on the initial interface, or something like that, when the application starts and detects that it would be a backup instance , this button would be visible with the option to enable the sending of commands to the CCG.

I don't know if I made myself understood, I would like your opinion on the possibility of implementing this functionality.

Thank you.

**Comment by jaskie** [comment]
The "backup instance" is designed to be started in case when main instance (i.e. whole machine) becomes nonoperational. In this case operator have time until current clip ends (it's assumed the second machine where is backup instance of TVPlay and primary CasparCG is working) to start the backup instance. If he start it on time, playout on the second machine will continue fluently. If not, the playout will be stopped at last frame of last clip started, and operator will have to start right item on rundown. 
The two instances (main and backup) both access database, and they don't know about each other. They are also not notified about database changes - database is only used as storage for objects persistent in memory (there is one exception from this rule). This approach works well, as ong as operator know what's going on (in most cases it's not so simple to determine if the primary machine is broken).
But introducing any other approach is not so simple, so I decided not to implement it now. 
If you need to be sure that controller is always operational, you can install it on HA VMware cluster. But you will introduce some more fault points (i.e. network switches). I assume you have read [wiki article on the topic](https://github.com/jaskie/PlayoutAutomation/wiki/Redundancy), just noted if not. I should add a diagram showing reference installation, I know...

**Comment by theusmpa** [comment]
I think I understand, you mean that if my main instance is closed (or the entire machine is inoperative for any other reason), the backup instance must take control of the rundown and the entire script that was in the main instance must be accessible in the instance backup?

Because if it is, here is a different behavior, the rundown is always empty in the backup instance ... I will perform new tests ...

I'm using the local SQLite database, the database needs to be in a separate bank to work correctly or has no relationship?

Thank you.

**Comment by jaskie** [comment]
Yes,
you need to have perpetually synchronized databases, so SQLite isn't option at all.
I was considering MySQL cluster, but this involved another points of failure. Then I decided to write wrapper to MySQL that performs all operations on two servers. So the MySQL driver allows two server connections. IMHO primary should be on local server where main instance of TVPlay runs, and backup - on remote server (I setup there also primary CasparCG player). The backup instance of TVPlay should be configured to use only backup server as primary (it may be on the same machine where the backup instance is prepared), as probably the other is dead at time when the backup instance is started.
For this reason, both server's media directories have to be defined (in TVPlay.config only) as UNC paths.
So I have two servers:
PRI: main CasparCG (with main PGM output), backup database, backup installation of TVPlay
SEC: backup CasparCG (with SEC and PRV outputs), main database, main installation of TVPlay.
Only caveat is to ensure that the primary instance is really dead when operator decides to run the backup...

**Comment by theusmpa** [comment]
Wonderful! I understood!

I will simulate this setup in my tests!

Tks!

--Matheus
