### ISSUE TITLE
GPI/GPO card

### ISSUE THREAD

**Issue by theusmpa** [jaskie/PlayoutAutomation#81]
Could you please give me details about how the application would work with a GPI / GPO command board?

Can I integrate with an MCR table? For example, when running LIVE events, can I set up unique GPOs for each type of Live Event? (Ex: LIVE X - GPO X, LIVE Y - GPO Y .. so on)?

Can I also trigger the playout server when receiving a GPI?

What are the compatible plate models?

How to make these settings in the application? (During my tests, I did not see any interface and found no information on the wiki)

As our resources are limited, I need to understand these details before investing in a card.

Thank you.

--Matheus

**Comment by jaskie** [comment]
Currently, there is only one GPI card partially supported - it's Advantech, tested with PCIe-1730. And it works only for starting playout when pins are short. There is relevant plugin available.
In near future, it's planned to add support for BMD and Ross switchers over network connection.
Now the live preselection is available for [BMD and Nevion routers](https://github.com/jaskie/PlayoutAutomation/wiki/Router).

**Comment by theusmpa** [comment]
ok, i'm looking forward to testing!

Thank you.
