### ISSUE TITLE
NDI preview TvPlayClient

### ISSUE THREAD

**Issue by theusmpa** [jaskie/PlayoutAutomation#85]
Hello!

In version 1.7.7369, I copied the plugins folder to TvPlayClient and the NDI preview worked.

In the last version, even copying the plugins, this functionality was not enabled, how to activate this feature to be used in tvPlayClient?

tks

--Matheus

**Comment by jaskie** [comment]
You have to copy the NDI plugin itself (`TAS.Client.NDIVideoPreview.dll`), and required libraries: `Processing.NDI.Lib.x64.dll` and `NAudio.dll` to `plugins` subdirectory. Have you all them there?

**Comment by theusmpa** [comment]
A thousand apologies ... my fault!

I was having the same dll problems blocked on my work notebook!

Now it's working, I only have the problem of the application crashing when I'm going to manipulate the preview channel, as already opened [here](https://github.com/jaskie/PlayoutAutomation/issues/76).

Thank you!

**Comment by jaskie** [comment]
Great. I'll look at the #76 tomorrow.
