### ISSUE TITLE
MySQL VS SQLite

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#88]
Hi,

Do you have any plan to remove MySQL?
Is SQLite is better then MySQL?
I dont see SQLite datebase redundancy option please correct me if i am wrong.

Regards,

Fahad

**Comment by jaskie** [comment]
Yes, you are right.
MySQL will remain, as there are not native means to connect SQLite on remote PC. This is required to make simple redundancy.
SQLite was introduced to speed up simple installation.
Kind regards,
Jurek

**Comment by sfahadshahzad** [comment]
Hi
Do SQLite have redundancy option if yes please guide.

Regards,

Fahad

**Comment by jaskie** [comment]
No, it don't have the option. SQLite is local database. However, it you copy the database file to other PC frequently, it may be somewhat like this. Personally, I never tested nor recommend it.
