### ISSUE TITLE
Unable to find tas.server table

### ISSUE THREAD

**Issue by djevo1** [jaskie/PlayoutAutomation#9]
I am attempting to install and keep  getting this issue. I am not sure if it is something on my end or an issue with the software.

**Comment by jaskie** [comment]
Did you created database using TAS.Config.exe application?

**Comment by djevo1** [comment]
That file isn't in the download. Only Tvplay.config

**Comment by jaskie** [comment]
Yes, that's the one I mean (TVPlay.config.exe).

**Comment by djevo1** [comment]
I have sent all the info via email to see if this can be figured out

**Comment by jaskie** [comment]
It denoted error in source code. Just try with new binaries (and new database too)

**Comment by susedx** [comment]
Hi, could you please advise me, how to config database? I created separate database schema in mysql, caspar_cg, exist some script, which will create tables etc. in it? Or how I should configure?

**Comment by jaskie** [comment]
Database schema for MySQL should be created using TVPlay.config.exe application using this button:
![obraz](https://user-images.githubusercontent.com/1919742/126985525-cf35c64d-0b44-49cf-a821-f50f87e6c816.png)
