### ISSUE TITLE
mySQL - database not up to date

### ISSUE THREAD

**Issue by susedx** [jaskie/PlayoutAutomation#93]
After I installed mysql, I got error: Connection successful, your database should be updated. After I click yes/ok, I got this:

![image](https://user-images.githubusercontent.com/42433082/126776737-27b162bf-dccc-47f7-8a22-f94195bead38.png)

What does it mean?

**Comment by susedx** [comment]
I see, that tables are missing, there are no tables, but I thought, it is supposed to be created automaticaly.

**Comment by jaskie** [comment]
The database table in MySql database shoudl be created using this button:
![image](https://user-images.githubusercontent.com/1919742/127875463-da544772-e422-4986-a189-7cac0de8fbb7.png)
You shouldn't create schema manually.

**Comment by susedx** [comment]
Thanks, already works to me fine. I have issues sending rtmp into wowza now, since wowza says stream is received, but test playout is not working (just black screen in player). But this is what I am trying to solve on the wowza forum. Have a nice day,P.Poslané z telefónu Orange-------- Pôvodná správa --------Od: Jerzy Jaśkiewicz ***@***.***>Dátum: po, 2. aug 2021, 16:15Pre: jaskie/PlayoutAutomation ***@***.***>Cc:  susedx ***@***.***>, Author ***@***.***>Predmet: Re: [jaskie/PlayoutAutomation] mySQL - database not up to date (#93)
The database table in MySql database shoudl be created using this button:

You shouldn't create schema manually.

**Comment by jaskie** [comment]
It's rather CasparCG issue. Until tightly integrated, the CasparCG and TVPlay needs to be configured separately, but accordingly.
Check if the played clips are actually played on CasparCG, e.g. using screen consumer. You can add screen consumer to running CasparCG using `ADD 1 SCREEN` (when `1` is channel index). If not, it's TVPlay and CasparCG misconfiguration, probably media directory paths points to different folders.
