### ISSUE TITLE
No Decklink Cards

### ISSUE THREAD

**Issue by Seyviour** [jaskie/PlayoutAutomation#94]
Is it possible to get TVPlay running without Decklink cards. Can we use NDI or screen consumers instead?

**Comment by jaskie** [comment]
Yes, it's possible.
TVPlay is only client to CasparCG, which have outputs. I recommend our CasparCG fork, which is attached to released binaries. It can output on Decklink, NDI, UDP and RTMP streams, as well as screen, and performs very well.

**Comment by Seyviour** [comment]
> Yes, it's possible.
> TVPlay is only client to CasparCG, which have outputs. I recommend our CasparCG fork, which is attached to released binaries. It can output on Decklink, NDI, UDP and RTMP streams, as well as screen, and performs very well.

Thanks of your response. TvPlay opens to a blank white screen for me. I thought the Decklink card (or lack thereof) might be the issue. Thanks for clarifying it isn't. Any idea what the problem might be? Thank you again !!!

**Comment by Seyviour** [comment]
Past the white screen. 😅 Turns out I had not configured properly. Current issue is that I can't seem to add clips (I've tried setting ingest and server folders but no luck yet)

**Comment by Seyviour** [comment]
Up and running. Thanks once again
