### ISSUE TITLE
NDI does not start

### ISSUE THREAD

**Issue by micail2** [jaskie/PlayoutAutomation#97]
Hi,
In my CasparCG NDI source does not start. 

I've tried various commands before...

<img width="747" alt="cg2" src="https://user-images.githubusercontent.com/100218471/155163749-3e0217c8-1e95-45a3-b0da-86c134be399e.PNG">

I even added an entry to the casparcg.config file, but I don't know how to enable it.

<img width="684" alt="cg1" src="https://user-images.githubusercontent.com/100218471/155163753-5dcf26a7-ddb1-470f-8dbb-db8f0ea0823e.PNG">

Thank you in advance and sorry for not understanding :(

**Comment by jaskie** [comment]
Hi,
sorry for poor documentation. The actual command is:
`PLAY|LOAD|LOADBG {channel}-{layer} [NDI] {source_name}`
i.e.: 
`PLAY 1-0 [NDI] "PC-523 (Decklink Duo (3) 3)"`
Note the square braces around _NDI_ and quotation marks around source name.
The source name is identical to the one presented on title bar in NDI Studio Monitor app:
![obraz](https://user-images.githubusercontent.com/1919742/155280182-870752ca-8318-4283-b6a6-29205438e929.png)
The same name can be used in caspar.config, but without qoutes.
It's possible to provide address to the consumer, it speeds up delivery of first video (ie. 6 -> 3 seconds).
Hope this help,
Jurek

**Comment by micail2** [comment]
Thanks. It worked!

Unfortunately, the sound stutters and in console errors appear.

<img width="971" alt="casparnew" src="https://user-images.githubusercontent.com/100218471/155810605-209974c7-bf4c-40d5-97bb-2a875c2263a5.PNG">

**Comment by jaskie** [comment]
I'll look at this. I have the same issue, it wasn't present earlier.

**Comment by jaskie** [comment]
Fixed in https://github.com/jaskie/Server/releases/tag/v8.4
